### ISSUE TITLE
Restarting animation upon getting into view

### ISSUE THREAD

**Issue by plavunov** [MickaelHrndz/entry#5] opened 2021-09-09 18:52 UTC
Hey, thanks for the package, fantastic work!

Do you have any ideas regarding the possibility to restart the animation each time the child widget fully gets back into the view (after being scrolled off the screen, for example)?

**Comment by MickaelHrndz** [comment] 2021-09-10 19:34
Hi, thank you ! I'm glad you like it :)
Could you provide me with a reproducible example ? I can't reproduce the animation not restarting in a ListView.

**Comment by MickaelHrndz** [comment] 2022-10-17 17:37
No answer for a year, I'm closing the issue.

**Closed as completed by MickaelHrndz** 2022-10-17 17:37 UTC
